import initImage from './init-det.jpg';

const IntroPanel = () => {

    return (
        <div id="intro-wrapper">
            <div id="intro-info-left" className="intro-info ls-only">
                <div>
                    <p>This image was generated by zooming in on the region;</p>
                </div>
                <div>
                    <p>Real axis:</p>
                    <p>-0.199 to -0.191</p>
                </div>
                <div>
                    <p>Imaginary axis:</p>
                    <p>0.665 to 0.675</p>
                </div>
            </div>
            <div>
                <img src={initImage} className='init-style' />
            </div>
            <div id="intro-info-right" className="intro-info ls-only">
                <div>
                    <p>The fractal is created using the famous Mandelbrot Equation.</p>
                </div>
                <div>
                    <p>Zn = Z^2 + C</p>
                </div>
                <div>
                    <p>To generate your own unique image, get started by choosing a color scheme and clicking begin.</p>
                </div>
            </div>
        </div>
    );
};

export default IntroPanel;